apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: pod
spec:
  containers:
    - name: python
      image: python:3.6-slim
      command:
        - cat
      tty: true
    - name: java
      image: openjdk:8-jre
      command:
        - cat
      tty: true
    - name: docker
      image: docker:dind
      command:
        - cat
      tty: true
      privileged: true
    - name: helm
      image: lachlanevenson/k8s-helm:v3.1.1
      command:
        - cat
      tty: true