openapi: "3.0.0"

info:
  version: 0.0.1
  title: HPC Gateway Interface
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

paths:
  
  /services:
    get:
      summary: "Get all available services"
      # security:
      #   - apiKey: [ ]
      #   - oauth2: [ email ]
      operationId: get_all_services
      responses:
        200:
          description: List of all available HPC services
          content:
            application/json:
              schema:
                type: array
                description: List of all available HPC services
                items:
                  $ref: '#/components/schemas/HPCService'
        401:
          description: Unauthorized request
          content:
            application/json:
              schema:
                type: string
        500:
          description: An error has occurred
          content:
            application/json:
              schema:
                type: string

components:

  schemas:

    HPCService:
      description: Description of the HPC service
      type: object
      required:
        - id
        - name
        - version
        - type
      properties:
        id:
          description: UUID of the service
          type: string
          format: uuid
        name:
          description: Name of the service
          $ref: "#/components/schemas/ServiceName"
        version:
          description: Version of the service
          type: string
        type:
          description: Type of the service
          $ref: "#/components/schemas/ServiceType"

    ServiceName:
      type: string
      enum:
        - kalman_filter
        - min_max_filter
        - fft_filter

    ServiceType:
      type: string
      enum:
        - filter

  # # In case the security mechanisms are needed to be implemented 
  # securitySchemes:
  #   apiKey:
  #     type: apiKey
  #     x-apikeyInfoFunc: hpc.api.service.security.check_api_key
  #     name: X-API-Key
  #     in: header
  #   oauth2:
  #     flows:
  #       password:
  #         tokenUrl: http://keycloak:8080/auth/realms/SERRANO/protocol/openid-connect/token
  #         scopes:
  #           email: Email of the user accessing the service.
  #     type: oauth2
  #     x-tokenInfoFunc: hpc.api.service.security.token_info
  #     x-scopeValidateFunc: hpc.api.service.security.validate_scope